Lido wstETH Plugin for Base
reserve-protocol/protocol pull request #1063
Opened 2024-02-07 11:55 UTC by akshatmittal

2024-02-07 21:48 UTC, tbrent approved these changes
LGTM.

2024-02-07 21:51 UTC, tbrent commented
I'm looking forward to the backtest so we can confirm this chainlink feed works the way we think it does.

2024-02-07 22:08 UTC, tbrent commented on test/plugins/individual-collateral/lido/L2LidoStakedEthTestSuite.test.ts
> +  revenueHiding: fp('0'), // TODO: how much?
Actually, this does need revenue hiding. 0.01%, or fp('1e-4'), to be consistent with mainnet

2024-02-07 23:34 UTC, pmckelvy1 commented on test/plugins/individual-collateral/lido/constants.ts
> +export const BASE_ORACLE_ERROR = fp('0.0115') // 0.5% + 0.5% + 0.15%
well technically slashing could occur, right? so we need a non-zero error

2024-02-07 23:53 UTC, pmckelvy1 requested changes

2024-02-07 23:53 UTC, pmckelvy1 commented on contracts/plugins/assets/lido/L2LidoStakedEthCollateral.sol
> +        return _safeWrap(refPerTokenChainlinkFeed.price(refPerTokenChainlinkTimeout));
no need to _safeWrap

2024-02-07 23:53 UTC, pmckelvy1 commented on test/plugins/individual-collateral/lido/L2LidoStakedEthTestSuite.test.ts
> +  refPerTokenChainlinkFeed: bn('1e18'), // ??
maybe 1.15e18 just to make it more realistic?

2024-02-07 23:53 UTC, pmckelvy1 commented on test/plugins/individual-collateral/lido/L2LidoStakedEthTestSuite.test.ts
> +  // TODO: Change this!
still need to change this?

2024-02-08 16:12 UTC, tbrent commented on test/plugins/individual-collateral/lido/constants.ts
> +export const BASE_ORACLE_ERROR = fp('0.0115') // 0.5% + 0.5% + 0.15%
Correct, just commenting on the weirdness

2024-02-08 20:46 UTC, pmckelvy1 commented
lgtm

2024-02-08 20:46 UTC, merged