Normal Ops additions
reserve-protocol/protocol pull request #341
Opened 2022-09-15 14:58 UTC by julianmrodri

* Setup StRSR as a registered token (so it is handled by echidna)
* Adds mutators for `distribute()` in Distributor and `manageToken()` in RevenueTrader.
* Adds tests for mutators

2022-09-23 06:18 UTC, fiddlemath reviewed
I didn't get through ChaosOps yet, but I took a look at everything else and made appropriate comments. All else looks good, and especially thank you for fixing the `between` bug everywhere!

2022-09-23 11:34 UTC, julianmrodri commented on contracts/fuzz/Utils.sol
> +function compareStr(string memory stringA, string memory stringB) pure returns (bool) {
Done.

2022-09-23 11:35 UTC, julianmrodri commented on contracts/fuzz/CollateralMock.sol
> +            uint192 p = (pricePerTarget() * targetPerRef()) / FIX_ONE;
Nice,if I do this then the `initialPeg` I store for comparison, should also only be the `targetPerRef()`.  Will implement.

2022-09-23 11:43 UTC, julianmrodri commented on contracts/fuzz/TradeMock.sol
> +        if (mode == SettlingMode.Acceptable) {
Isnt this going to get the "correct" value only 1 out of 5 times for the `Random` mode? Was that the intended behavior or we should be using `> 0`?

2022-09-23 11:55 UTC, julianmrodri commented on contracts/fuzz/TradeMock.sol
> +            );
Yes, i wanted to allow it just a bit under the `minBuyAmount` to reduce the number of times this fails. But if we enforce that in another place we can fully randomize.

2022-09-23 12:02 UTC, julianmrodri commented on contracts/fuzz/TradeMock.sol
> +            actualBuyAmt = between(buyAmt, (buyAmt * (FIX_ONE + maxTradeSlippage)) / FIX_ONE, seed);
Done

2022-09-23 16:34 UTC, julianmrodri commented on contracts/fuzz/TradeMock.sol
> +        if (mode == SettlingMode.Acceptable) {
converting to > 0 as we talked

2022-09-23 18:42 UTC, fiddlemath reviewed
OK, the whole ChaosOps scenario looks pretty solid to me, modulo the changes to asset registration that we already talked about. 👍

2022-09-23 18:42 UTC, fiddlemath commented on contracts/fuzz/scenarios/ChaosOps.sol
> +        bool switchType = (switchTypeSeed %= 100) <= 1;
This will make switchType true 2 out of 100 times -- which is fine, but violates the stated intent.

2022-09-23 18:42 UTC, fiddlemath commented on contracts/fuzz/scenarios/ChaosOps.sol
> +        bool switchType = (switchTypeSeed %= 100) <= 1;
Also, using the `%=` operator here is slightly funky; why not just `%`?

2022-09-28 18:21 UTC, fiddlemath requested changes
I've got some style qualms with the way the invariant implementations, but otherwise the sense of all of this code seems good.

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +        bool maxTradeSlippageProp = (maxTradeSlippage > MAX_TRADE_SLIPPAGE) ? false : true;
```suggestion
        bool tradingDelayProp = tradingDelay <= MAX_TRADING_DELAY;
        bool backingBufferProp = backingBuffer <= MAX_BACKING_BUFFER;
        bool maxTradeSlippageProp = maxTradeSlippage <= MAX_TRADE_SLIPPAGE;
```

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +        bool disabledIfEmptyProp = (basket.erc20s.length == 0 && !basket.disabled) ? false : true;
```suggestion
        bool disabledIfEmptyProp = basket.erc20s.length > 0 || basket.disabled;
```

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +            : true;
```suggestion
        bool auctionLengthProp = auctionLength > 0 && auctionLength <= MAX_AUCTION_LENGTH;
```

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +            : true;
```suggestion
        bool distNotEmptyProp = !(revTotals.rTokenTotal == 0 && revTotals.rsrTotal == 0);
```

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +            : true;
```suggestion
        bool noInvalidDistProp = distribution[FURNACE].rsrDist == 0 &&
            distribution[ST_RSR].rTokenDist == 0;
```

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +        bool maxTradeSlippageProp = (maxTradeSlippage > MAX_TRADE_SLIPPAGE) ? false : true;
```suggestion
        bool maxTradeSlippageProp = maxTradeSlippage <= MAX_TRADE_SLIPPAGE;
```

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +        }
```suggestion
        bool totalStakesCovered = stakeRSR * stakeRate >= totalStakes * 1e18;
```

2022-09-28 18:21 UTC, fiddlemath commented on contracts/fuzz/FuzzP1.sol
> +        }
```suggestion
        bool totalDraftsCovered = draftRSR * draftRate >= totalDrafts * 1e18;
```

2022-09-29 13:18 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +        bool maxTradeSlippageProp = (maxTradeSlippage > MAX_TRADE_SLIPPAGE) ? false : true;
Done

2022-09-29 13:19 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +        bool disabledIfEmptyProp = (basket.erc20s.length == 0 && !basket.disabled) ? false : true;
Done

2022-09-29 13:20 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +            : true;
Done

2022-09-29 13:21 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +            : true;
Done

2022-09-29 13:22 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +            : true;
Done

2022-09-29 13:22 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +        bool maxTradeSlippageProp = (maxTradeSlippage > MAX_TRADE_SLIPPAGE) ? false : true;
Done

2022-09-29 13:24 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +        }
Done

2022-09-29 13:24 UTC, julianmrodri commented on contracts/fuzz/FuzzP1.sol
> +        }
Done

2022-11-04 16:08 UTC, fiddlemath approved these changes

2022-11-04 17:03 UTC, julianmrodri commented
Merging to `fuzz` based on offline conversations.

2022-11-04 17:04 UTC, merged