Feature/plugin convex
reserve-protocol/protocol pull request #636
Opened 2023-02-14 22:38 UTC by tbrent

2023-03-16 02:22 UTC, pmckelvy1 requested changes

2023-03-16 02:22 UTC, pmckelvy1 commented on contracts/plugins/assets/convex/PoolTokens.sol
> +    function tokenPrice(uint8 index) public view returns (uint192 low, uint192 high) {
add doc for param

2023-03-16 02:22 UTC, pmckelvy1 commented on contracts/plugins/assets/convex/PoolTokens.sol
> +    // returns low and high extremes of x * y, given errors
fix up docs

2023-03-16 02:22 UTC, pmckelvy1 commented on contracts/plugins/assets/convex/PoolTokens.sol
> +    function maxFeedsLength(AggregatorV3Interface[][] memory feeds) private pure returns (uint8) {
docs

2023-03-16 02:22 UTC, pmckelvy1 commented on contracts/plugins/assets/convex/PoolTokens.sol
> +    function minFeedsLength(AggregatorV3Interface[][] memory feeds) private pure returns (uint8) {
docs

2023-03-16 02:22 UTC, pmckelvy1 commented on contracts/plugins/assets/convex/PoolTokens.sol
> +    function getToken(uint8 index) private view returns (IERC20Metadata) {
docs

2023-03-16 02:22 UTC, pmckelvy1 commented on contracts/plugins/assets/convex/CvxStableCollateral.sol
> +        aumLow = aumLow.mulDiv(exposedReferencePrice, _underlyingRefPerTok());
why not just `aumLow.mul(revenueShowing)`?

2023-03-16 02:22 UTC, pmckelvy1 commented on contracts/plugins/assets/convex/CvxVolatileCollateral.sol
> +                uint192 mid = low + high / 2;
need parens `uint192 mid = (low + high) / 2;`

2023-03-20 16:15 UTC, tbrent commented on scripts/deployment/phase2-assets/collaterals/deploy_convex_stable_plugin.ts
> +    bn('1e14'), // revenueHiding = 0.01%
We should either remove revenueHiding entirely or set it to the value in `scripts/deployment/utils.ts` (fp('1e-6')), given that we think the virtual price cannot decrease.

2023-03-28 00:23 UTC, tbrent commented
@akshatmittal verification script for 3pool is missing btw

2023-03-28 17:46 UTC, pmckelvy1 commented
lgtm

2023-03-28 23:05 UTC, merged