Adjust dutch auction curve to defend against manipulated prices
reserve-protocol/protocol pull request #828
Opened 2023-05-18 16:01 UTC by tbrent

This curve can handle manipulated prices of 1000x. During the first 40% of the auction the price decrease by 10% each block, resulting in a worst-case precision loss of 10% and avg case 5%. During the last 60% of the auction the price decreases by ~0.05% each block. Auctions last 30 minutes, and they do sane things if governance configures a different value.

2023-05-18 22:06 UTC, pmckelvy1 requested changes

2023-05-18 22:06 UTC, pmckelvy1 commented on test/Revenues.test.ts
> +            console.log(actual)
delete

2023-05-20 15:06 UTC, tbrent commented
New auction sample, at 40%/60% + 30 minutes
Drops are ~10% during the geometric phase and ~0.05% during the linear phase

```
BigNumber { value: "10202021986314579853800" }
BigNumber { value: "9092563458173149552760" }
BigNumber { value: "8103757309267611323150" }
BigNumber { value: "7222475505254277247500" }
BigNumber { value: "6437039338350703645630" }
BigNumber { value: "5737018479790004552120" }
BigNumber { value: "5113124109924278498180" }
BigNumber { value: "4557077557896574467960" }
BigNumber { value: "4061496387584514970280" }
BigNumber { value: "3619813179072919850870" }
BigNumber { value: "3226162527546344059560" }
BigNumber { value: "2875320945930658453220" }
BigNumber { value: "2562632995553202332050" }
BigNumber { value: "2283947227562289822460" }
BigNumber { value: "2035570510393566222570" }
BigNumber { value: "1814204484578406273510" }
BigNumber { value: "1616911767516242077590" }
BigNumber { value: "1441074413692702447830" }
BigNumber { value: "1284357891893095891810" }
BigNumber { value: "1144685401649689218570" }
BigNumber { value: "1020202139154974748370" }
BigNumber { value: "909256292808833099550" }
BigNumber { value: "810375683682892847010" }
BigNumber { value: "722247508419319884070" }
BigNumber { value: "643703896307954532780" }
BigNumber { value: "573701814532916743720" }
BigNumber { value: "511312381183568649510" }
BigNumber { value: "455707729222478519980" }
BigNumber { value: "406149615080447244420" }
BigNumber { value: "361981296804244432830" }
BigNumber { value: "322616233946519712130" }
BigNumber { value: "287532077830312719410" }
BigNumber { value: "256263284615497820590" }
BigNumber { value: "228394709441108957230" }
BigNumber { value: "203557039172241059120" }
BigNumber { value: "181420437881260646440" }
BigNumber { value: "161691167325235528810" }
BigNumber { value: "144107432967990834460" }
BigNumber { value: "128435781701667449440" }
BigNumber { value: "114468533491599524700" }
BigNumber { value: "102020207967849574270" }
BigNumber { value: "90925623980035493670" }
BigNumber { value: "81037563643902761770" }
BigNumber { value: "72224746631321449860" }
BigNumber { value: "64370385878084120830" }
BigNumber { value: "57370178108683519630" }
BigNumber { value: "51131235137471122590" }
BigNumber { value: "45570770265530113160" }
BigNumber { value: "40614959140244449150" }
BigNumber { value: "36198127570119810310" }
BigNumber { value: "32261621513840616870" }
BigNumber { value: "28753206106756057480" }
BigNumber { value: "25626326967567630160" }
BigNumber { value: "22839469612598970500" }
BigNumber { value: "20355702730512619820" }
BigNumber { value: "18142042730468130680" }
BigNumber { value: "16169115789884741440" }
BigNumber { value: "14410742456671192900" }
BigNumber { value: "12843577421402575530" }
BigNumber { value: "11446852681823052500" }
BigNumber { value: "10202020202020202030" }
BigNumber { value: "10196486215165082190" }
BigNumber { value: "10190952228309962340" }
BigNumber { value: "10185418241454842490" }
BigNumber { value: "10179884254599722650" }
BigNumber { value: "10174350267744602800" }
BigNumber { value: "10168816280889482950" }
BigNumber { value: "10163282294034363110" }
BigNumber { value: "10157748307179243260" }
BigNumber { value: "10152214320324123410" }
BigNumber { value: "10146680333469003570" }
BigNumber { value: "10141146346613883720" }
BigNumber { value: "10135612359758763870" }
BigNumber { value: "10130078372903644030" }
BigNumber { value: "10124544386048524180" }
BigNumber { value: "10119010399193404330" }
BigNumber { value: "10113476412338284490" }
BigNumber { value: "10107942425483164640" }
BigNumber { value: "10102408438628044790" }
BigNumber { value: "10096874451772924950" }
BigNumber { value: "10091340464917805100" }
BigNumber { value: "10085806478062685250" }
BigNumber { value: "10080272491207565410" }
BigNumber { value: "10074738504352445560" }
BigNumber { value: "10069204517497325710" }
BigNumber { value: "10063670530642205870" }
BigNumber { value: "10058136543787086020" }
BigNumber { value: "10052602556931966170" }
BigNumber { value: "10047068570076846330" }
BigNumber { value: "10041534583221726480" }
BigNumber { value: "10036000596366606630" }
BigNumber { value: "10030466609511486790" }
BigNumber { value: "10024932622656366940" }
BigNumber { value: "10019398635801247090" }
BigNumber { value: "10013864648946127250" }
BigNumber { value: "10008330662091007400" }
BigNumber { value: "10002796675235887550" }
BigNumber { value: "9997262688380767710" }
BigNumber { value: "9991728701525647860" }
BigNumber { value: "9986194714670528010" }
BigNumber { value: "9980660727815408170" }
BigNumber { value: "9975126740960288320" }
BigNumber { value: "9969592754105168470" }
BigNumber { value: "9964058767250048630" }
BigNumber { value: "9958524780394928780" }
BigNumber { value: "9952990793539808930" }
BigNumber { value: "9947456806684689090" }
BigNumber { value: "9941922819829569240" }
BigNumber { value: "9936388832974449390" }
BigNumber { value: "9930854846119329550" }
BigNumber { value: "9925320859264209700" }
BigNumber { value: "9919786872409089850" }
BigNumber { value: "9914252885553970010" }
BigNumber { value: "9908718898698850160" }
BigNumber { value: "9903184911843730310" }
BigNumber { value: "9897650924988610470" }
BigNumber { value: "9892116938133490620" }
BigNumber { value: "9886582951278370770" }
BigNumber { value: "9881048964423250930" }
BigNumber { value: "9875514977568131080" }
BigNumber { value: "9869980990713011230" }
BigNumber { value: "9864447003857891390" }
BigNumber { value: "9858913017002771540" }
BigNumber { value: "9853379030147651690" }
BigNumber { value: "9847845043292531850" }
BigNumber { value: "9842311056437412000" }
BigNumber { value: "9836777069582292150" }
BigNumber { value: "9831243082727172310" }
BigNumber { value: "9825709095872052460" }
BigNumber { value: "9820175109016932610" }
BigNumber { value: "9814641122161812770" }
BigNumber { value: "9809107135306692920" }
BigNumber { value: "9803573148451573070" }
BigNumber { value: "9798039161596453230" }
BigNumber { value: "9792505174741333380" }
BigNumber { value: "9786971187886213530" }
BigNumber { value: "9781437201031093690" }
BigNumber { value: "9775903214175973840" }
BigNumber { value: "9770369227320853990" }
BigNumber { value: "9764835240465734150" }
BigNumber { value: "9759301253610614300" }
BigNumber { value: "9753767266755494450" }
BigNumber { value: "9748233279900374610" }
BigNumber { value: "9742699293045254760" }
BigNumber { value: "9737165306190134910" }
BigNumber { value: "9731631319335015070" }
BigNumber { value: "9726097332479895220" }
BigNumber { value: "9720563345624775370" }
BigNumber { value: "9715029358769655530" }
BigNumber { value: "9709495371914535680" }
BigNumber { value: "9703961385059415830" }
```

2023-05-20 16:04 UTC, tbrent commented
The geometric decay curve is no longer highly sensitive to the exact auction length used. There is now enough precision in its expoenent for it to handle any length up to auctions of 1 week.

2023-05-20 17:55 UTC, merged