Report Violation Per Trade
reserve-protocol/protocol pull request #869
Opened 2023-07-25 20:21 UTC by akshatmittal

Resolves https://github.com/code-423n4/2023-06-reserve-findings/issues/47

2023-07-26 20:01 UTC, tbrent commented on contracts/interfaces/IBroker.sol
> +    event DisabledSet(TradeKind tradeKind, bool indexed prevVal, bool indexed newVal);
Should be indexed I think

2023-07-26 20:38 UTC, pmckelvy1 requested changes

2023-07-26 20:38 UTC, pmckelvy1 commented on contracts/p0/Broker.sol
> +        require(!tradeKindDisabled[kind], "broker disabled");
"broker disabled for that trade kind"

2023-07-26 20:39 UTC, tbrent commented on test/Broker.test.ts
> +      await expect(broker.connect(owner).setDisabled(TradeKind.DUTCH_AUCTION, true))
I'm going to tweak these tests to test each kind separately

2023-07-27 19:58 UTC, pmckelvy1 commented
github seems to be having an issue showing the proper diffs but they pull correctly so im going to merge

lgtm

2023-07-27 19:58 UTC, merged

2023-07-27 22:18 UTC, tbrent commented
Oh I wasn't planning on merging this if we accepted #869, since they're basically mutually exclusive changes. I should be able to merge it though, just will take some work...

2023-07-28 02:26 UTC, akshatmittal commented
Yeah I was also going to close this in favor of #869. Seems ok, should be fine.