draft max custom redeem algo; might have to go in new Facade
reserve-protocol/protocol pull request #959
Opened 2023-10-03 15:59 UTC by tbrent

2023-10-04 16:52 UTC, tbrent commented
After approval I'll deploy

2023-10-05 15:55 UTC, pmckelvy1 requested changes

2023-10-05 15:55 UTC, pmckelvy1 commented on contracts/facade/FacadeMint.sol
> +        // Walk backwards from current nonce, deducting from basketsNeeded greedily
comment is wrong. seems we're walking forward instead

2023-10-05 15:55 UTC, pmckelvy1 commented on test/Facade.test.ts
> +      itP1('Should calculate customRedeem portions correctly', async () => {
seems like we should also test at least 1 or 2 scenarios that are a little more complex than this?

2023-10-05 21:56 UTC, tbrent commented
@akshatmittal @pmckelvy1 this algo turns out to be insufficient. Going either solely forwards or backwards does not work all the time. I think the fastest simple algo is `O(n^2)`: you have to pass over each basket nonce and choose the one with the max number of baskets given current available balances, and you have to do this for every single choice of next basket nonce to use. 

I could imagine discovering there's a `O(n*log(n)) algo somewhere out there if you do a sort on some clever computed metric, but a simple `O(n)` algo does not exist pretty sure.

2023-10-05 22:02 UTC, tbrent commented
One not so crazy option is to limit the search to the past `n` basket nonces, where `n` is something like 3 or 5. Or at least, we'd take this as an argument and leave it to the off-chain component to decide which `n` to use.

2023-10-05 22:04 UTC, tbrent commented
This is absolutely a sign that this problem is best-solved fully from off-chain, though.

2023-10-05 22:13 UTC, akshatmittal commented
I think so too, this should be off-chain ideally. Seems my doubts were reasonable, thanks for looking into it!

2023-10-05 22:38 UTC, tbrent commented
I went to start writing the `O(n^2)` solution and it very quickly got past the stack limit. We should close out this PR and not use it. This also means we don't have to split up `FacadeRead` just yet.

2023-10-05 22:38 UTC, closed without merging